server:
  port: 7070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: admin-service
        uri: lb://admin-service
        predicates:
        - Path=/api/admin/**
         
      - id: jobseeker-service
        uri: lb://jobseeker-service
        predicates:
        - Path= /api/jobseeker/**
        
      - id: employer-service
        uri: lb://employer-service
        predicates:
        - Path= /api/employer/**
        
      - id: registration-service
        uri: lb://registration-service
        predicates:
        - Path= /api/registration/employer/**
        
        
      