server:
  port: 7070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: admin-service
        uri: lb://admin-service
        predicates:
        - Path=/api/admin/**,/api/admin/approval/requests/**,/api/admin/approval/requests/accept/{username}/**,
               /api/admin/approval/requests/delete/{username},/api/admin/user/block/{username}
        filters:
        - RewritePath=/institutes/(?<path>.*), /$\{path}
        
      - id: seeker-service
        uri: lb://seeker-service
        predicates:
        - Path= /api/jobseeker/**,/api/jobseeker/updatepersonaldetails/**,/api/jobseeker/updateeducationdetails/**,
                /api/jobseeker/updateworkexperiancedetails/**,/api/jobseeker/applyforjob/**,
                /api/jobseeker/givefeedback/**,/api/jobseeker/getprofiledetails/**,api/jobseeker/getsearchedjobs/**
        filters:
        - RewritePath=/institutes/(?<path>.*), /$\{path}
        
        
      - id: employer-service
        uri: lb://employer-service
        predicates:
        - Path= /api/employer/**,/api/employer/updatecompanydetails/**,api/employer/postjobs/**
                api/employer/removejob/**,api/employer/getpostedjobs/**
        filters:
        - RewritePath=/institutes/(?<path>.*), /$\{path}
        
      - id: registration-service
        uri: lb://registration-service
        predicates:
        - Path= /api/registration/employer/**,/api/admin/requests/**,/api/jobseeker/updatepersonaldetails/**
        filters:
        - RewritePath=/institutes/(?<path>.*), /$\{path}
        
        
        
      